import java.util.Random;
/**
 *  Computes some statistics about families in which the parents decide 
 *  to have children until they have at least one child of each gender.
 *  The program expects to get two command-line arguments: an int value
 * 	that determines how many families to simulate, and an int value
 *  that serves as the seed of the random numbers generated by the program.
 *  Example usage: % java OneOfEachStats 1000 1
 */
public class OneOfEachStats {
	public static void main (String[] args) {
		int T = Integer.parseInt(args[0]);
		int seed = Integer.parseInt(args[1]);
        Random generator = new Random(seed);
		int boysInFamily = 0, girlsInFamily = 0;
		int totalKids = 0;
		int twoChildren = 0, threeChildren = 0, fourOrMoreChildren = 0;
		double avarageChildrenPerFamily;

		for (int i = 0; i < T; i++) {	
			
			while (boysInFamily == 0 || girlsInFamily == 0) {
				double x = generator.nextDouble();
				if(x < 0.5) {
					boysInFamily++;
					totalKids++;
				}
				else {
					girlsInFamily++;
					totalKids++;
				}
			}

			if(boysInFamily + girlsInFamily == 2) {
				twoChildren++;
			}
			else if (boysInFamily + girlsInFamily == 3) {
				threeChildren++;
			}
			else {
				fourOrMoreChildren++;
			}

			boysInFamily = 0;
			girlsInFamily = 0;
		}

		avarageChildrenPerFamily = (double)totalKids / (double)T;

		System.out.println("Average: " + avarageChildrenPerFamily + " children to get at least one of each gender.");
		System.out.println("Number of families with 2 children: " + twoChildren);
		System.out.println("Number of families with 3 children: " + threeChildren);
		System.out.println("Number of families with 4 or more children: " + fourOrMoreChildren);

		if (twoChildren > threeChildren && twoChildren > fourOrMoreChildren) {
			System.out.println("The most common number of children is 2.");	
		}
		else if (threeChildren > twoChildren && threeChildren > fourOrMoreChildren) {
			System.out.println("The most common number of children is 3.");
		}
		else {
			System.out.println("The most common number of children is 4 or more.");
		}
	}    
}